/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NetWork.Auto
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCSyncPlayerInfo : TBase
  {
    private NetWork.Auto.PlayerInfo _playerInfomation;

    public NetWork.Auto.PlayerInfo PlayerInfomation
    {
      get
      {
        return _playerInfomation;
      }
      set
      {
        __isset.playerInfomation = true;
        this._playerInfomation = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool playerInfomation;
    }

    public SCSyncPlayerInfo() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.Struct) {
              PlayerInfomation = new NetWork.Auto.PlayerInfo();
              PlayerInfomation.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCSyncPlayerInfo");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (PlayerInfomation != null && __isset.playerInfomation) {
        field.Name = "playerInfomation";
        field.Type = TType.Struct;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        PlayerInfomation.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCSyncPlayerInfo(");
      sb.Append("PlayerInfomation: ");
      sb.Append(PlayerInfomation== null ? "<null>" : PlayerInfomation.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }

}
