/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class AIConfigTable implements org.apache.thrift.TBase<AIConfigTable, AIConfigTable._Fields>, java.io.Serializable, Cloneable, Comparable<AIConfigTable> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AIConfigTable");

  private static final org.apache.thrift.protocol.TField BT_TREE_XML_FIELD_DESC = new org.apache.thrift.protocol.TField("btTreeXml", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new AIConfigTableStandardSchemeFactory());
    schemes.put(TupleScheme.class, new AIConfigTableTupleSchemeFactory());
  }

  public String btTreeXml; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    BT_TREE_XML((short)1, "btTreeXml");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BT_TREE_XML
          return BT_TREE_XML;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BT_TREE_XML, new org.apache.thrift.meta_data.FieldMetaData("btTreeXml", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AIConfigTable.class, metaDataMap);
  }

  public AIConfigTable() {
  }

  public AIConfigTable(
    String btTreeXml)
  {
    this();
    this.btTreeXml = btTreeXml;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AIConfigTable(AIConfigTable other) {
    if (other.isSetBtTreeXml()) {
      this.btTreeXml = other.btTreeXml;
    }
  }

  public AIConfigTable deepCopy() {
    return new AIConfigTable(this);
  }

  @Override
  public void clear() {
    this.btTreeXml = null;
  }

  public String getBtTreeXml() {
    return this.btTreeXml;
  }

  public AIConfigTable setBtTreeXml(String btTreeXml) {
    this.btTreeXml = btTreeXml;
    return this;
  }

  public void unsetBtTreeXml() {
    this.btTreeXml = null;
  }

  /** Returns true if field btTreeXml is set (has been assigned a value) and false otherwise */
  public boolean isSetBtTreeXml() {
    return this.btTreeXml != null;
  }

  public void setBtTreeXmlIsSet(boolean value) {
    if (!value) {
      this.btTreeXml = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case BT_TREE_XML:
      if (value == null) {
        unsetBtTreeXml();
      } else {
        setBtTreeXml((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case BT_TREE_XML:
      return getBtTreeXml();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case BT_TREE_XML:
      return isSetBtTreeXml();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof AIConfigTable)
      return this.equals((AIConfigTable)that);
    return false;
  }

  public boolean equals(AIConfigTable that) {
    if (that == null)
      return false;

    boolean this_present_btTreeXml = true && this.isSetBtTreeXml();
    boolean that_present_btTreeXml = true && that.isSetBtTreeXml();
    if (this_present_btTreeXml || that_present_btTreeXml) {
      if (!(this_present_btTreeXml && that_present_btTreeXml))
        return false;
      if (!this.btTreeXml.equals(that.btTreeXml))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(AIConfigTable other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetBtTreeXml()).compareTo(other.isSetBtTreeXml());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBtTreeXml()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.btTreeXml, other.btTreeXml);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("AIConfigTable(");
    boolean first = true;

    sb.append("btTreeXml:");
    if (this.btTreeXml == null) {
      sb.append("null");
    } else {
      sb.append(this.btTreeXml);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AIConfigTableStandardSchemeFactory implements SchemeFactory {
    public AIConfigTableStandardScheme getScheme() {
      return new AIConfigTableStandardScheme();
    }
  }

  private static class AIConfigTableStandardScheme extends StandardScheme<AIConfigTable> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, AIConfigTable struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // BT_TREE_XML
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.btTreeXml = iprot.readString();
              struct.setBtTreeXmlIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, AIConfigTable struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.btTreeXml != null) {
        oprot.writeFieldBegin(BT_TREE_XML_FIELD_DESC);
        oprot.writeString(struct.btTreeXml);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AIConfigTableTupleSchemeFactory implements SchemeFactory {
    public AIConfigTableTupleScheme getScheme() {
      return new AIConfigTableTupleScheme();
    }
  }

  private static class AIConfigTableTupleScheme extends TupleScheme<AIConfigTable> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, AIConfigTable struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetBtTreeXml()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetBtTreeXml()) {
        oprot.writeString(struct.btTreeXml);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, AIConfigTable struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.btTreeXml = iprot.readString();
        struct.setBtTreeXmlIsSet(true);
      }
    }
  }

}

