/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class GrenadeConfigTable implements org.apache.thrift.TBase<GrenadeConfigTable, GrenadeConfigTable._Fields>, java.io.Serializable, Cloneable, Comparable<GrenadeConfigTable> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("GrenadeConfigTable");

  private static final org.apache.thrift.protocol.TField GRENADE_CONFIG_FIELD_DESC = new org.apache.thrift.protocol.TField("grenadeConfig", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new GrenadeConfigTableStandardSchemeFactory());
    schemes.put(TupleScheme.class, new GrenadeConfigTableTupleSchemeFactory());
  }

  public List<GrenadeConfig> grenadeConfig; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    GRENADE_CONFIG((short)1, "grenadeConfig");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // GRENADE_CONFIG
          return GRENADE_CONFIG;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.GRENADE_CONFIG, new org.apache.thrift.meta_data.FieldMetaData("grenadeConfig", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, GrenadeConfig.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(GrenadeConfigTable.class, metaDataMap);
  }

  public GrenadeConfigTable() {
  }

  public GrenadeConfigTable(
    List<GrenadeConfig> grenadeConfig)
  {
    this();
    this.grenadeConfig = grenadeConfig;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public GrenadeConfigTable(GrenadeConfigTable other) {
    if (other.isSetGrenadeConfig()) {
      List<GrenadeConfig> __this__grenadeConfig = new ArrayList<GrenadeConfig>(other.grenadeConfig.size());
      for (GrenadeConfig other_element : other.grenadeConfig) {
        __this__grenadeConfig.add(new GrenadeConfig(other_element));
      }
      this.grenadeConfig = __this__grenadeConfig;
    }
  }

  public GrenadeConfigTable deepCopy() {
    return new GrenadeConfigTable(this);
  }

  @Override
  public void clear() {
    this.grenadeConfig = null;
  }

  public int getGrenadeConfigSize() {
    return (this.grenadeConfig == null) ? 0 : this.grenadeConfig.size();
  }

  public java.util.Iterator<GrenadeConfig> getGrenadeConfigIterator() {
    return (this.grenadeConfig == null) ? null : this.grenadeConfig.iterator();
  }

  public void addToGrenadeConfig(GrenadeConfig elem) {
    if (this.grenadeConfig == null) {
      this.grenadeConfig = new ArrayList<GrenadeConfig>();
    }
    this.grenadeConfig.add(elem);
  }

  public List<GrenadeConfig> getGrenadeConfig() {
    return this.grenadeConfig;
  }

  public GrenadeConfigTable setGrenadeConfig(List<GrenadeConfig> grenadeConfig) {
    this.grenadeConfig = grenadeConfig;
    return this;
  }

  public void unsetGrenadeConfig() {
    this.grenadeConfig = null;
  }

  /** Returns true if field grenadeConfig is set (has been assigned a value) and false otherwise */
  public boolean isSetGrenadeConfig() {
    return this.grenadeConfig != null;
  }

  public void setGrenadeConfigIsSet(boolean value) {
    if (!value) {
      this.grenadeConfig = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case GRENADE_CONFIG:
      if (value == null) {
        unsetGrenadeConfig();
      } else {
        setGrenadeConfig((List<GrenadeConfig>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case GRENADE_CONFIG:
      return getGrenadeConfig();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case GRENADE_CONFIG:
      return isSetGrenadeConfig();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof GrenadeConfigTable)
      return this.equals((GrenadeConfigTable)that);
    return false;
  }

  public boolean equals(GrenadeConfigTable that) {
    if (that == null)
      return false;

    boolean this_present_grenadeConfig = true && this.isSetGrenadeConfig();
    boolean that_present_grenadeConfig = true && that.isSetGrenadeConfig();
    if (this_present_grenadeConfig || that_present_grenadeConfig) {
      if (!(this_present_grenadeConfig && that_present_grenadeConfig))
        return false;
      if (!this.grenadeConfig.equals(that.grenadeConfig))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(GrenadeConfigTable other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetGrenadeConfig()).compareTo(other.isSetGrenadeConfig());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGrenadeConfig()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.grenadeConfig, other.grenadeConfig);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("GrenadeConfigTable(");
    boolean first = true;

    sb.append("grenadeConfig:");
    if (this.grenadeConfig == null) {
      sb.append("null");
    } else {
      sb.append(this.grenadeConfig);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class GrenadeConfigTableStandardSchemeFactory implements SchemeFactory {
    public GrenadeConfigTableStandardScheme getScheme() {
      return new GrenadeConfigTableStandardScheme();
    }
  }

  private static class GrenadeConfigTableStandardScheme extends StandardScheme<GrenadeConfigTable> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, GrenadeConfigTable struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // GRENADE_CONFIG
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list300 = iprot.readListBegin();
                struct.grenadeConfig = new ArrayList<GrenadeConfig>(_list300.size);
                for (int _i301 = 0; _i301 < _list300.size; ++_i301)
                {
                  GrenadeConfig _elem302;
                  _elem302 = new GrenadeConfig();
                  _elem302.read(iprot);
                  struct.grenadeConfig.add(_elem302);
                }
                iprot.readListEnd();
              }
              struct.setGrenadeConfigIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, GrenadeConfigTable struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.grenadeConfig != null) {
        oprot.writeFieldBegin(GRENADE_CONFIG_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.grenadeConfig.size()));
          for (GrenadeConfig _iter303 : struct.grenadeConfig)
          {
            _iter303.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class GrenadeConfigTableTupleSchemeFactory implements SchemeFactory {
    public GrenadeConfigTableTupleScheme getScheme() {
      return new GrenadeConfigTableTupleScheme();
    }
  }

  private static class GrenadeConfigTableTupleScheme extends TupleScheme<GrenadeConfigTable> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, GrenadeConfigTable struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetGrenadeConfig()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetGrenadeConfig()) {
        {
          oprot.writeI32(struct.grenadeConfig.size());
          for (GrenadeConfig _iter304 : struct.grenadeConfig)
          {
            _iter304.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, GrenadeConfigTable struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list305 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.grenadeConfig = new ArrayList<GrenadeConfig>(_list305.size);
          for (int _i306 = 0; _i306 < _list305.size; ++_i306)
          {
            GrenadeConfig _elem307;
            _elem307 = new GrenadeConfig();
            _elem307.read(iprot);
            struct.grenadeConfig.add(_elem307);
          }
        }
        struct.setGrenadeConfigIsSet(true);
      }
    }
  }

}

