/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class LimitConfgTable implements org.apache.thrift.TBase<LimitConfgTable, LimitConfgTable._Fields>, java.io.Serializable, Cloneable, Comparable<LimitConfgTable> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("LimitConfgTable");

  private static final org.apache.thrift.protocol.TField LIMIT_MAP_FIELD_DESC = new org.apache.thrift.protocol.TField("limitMap", org.apache.thrift.protocol.TType.MAP, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new LimitConfgTableStandardSchemeFactory());
    schemes.put(TupleScheme.class, new LimitConfgTableTupleSchemeFactory());
  }

  public Map<Integer,LimitGroup> limitMap; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LIMIT_MAP((short)1, "limitMap");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LIMIT_MAP
          return LIMIT_MAP;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LIMIT_MAP, new org.apache.thrift.meta_data.FieldMetaData("limitMap", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LimitGroup.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(LimitConfgTable.class, metaDataMap);
  }

  public LimitConfgTable() {
  }

  public LimitConfgTable(
    Map<Integer,LimitGroup> limitMap)
  {
    this();
    this.limitMap = limitMap;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public LimitConfgTable(LimitConfgTable other) {
    if (other.isSetLimitMap()) {
      Map<Integer,LimitGroup> __this__limitMap = new HashMap<Integer,LimitGroup>(other.limitMap.size());
      for (Map.Entry<Integer, LimitGroup> other_element : other.limitMap.entrySet()) {

        Integer other_element_key = other_element.getKey();
        LimitGroup other_element_value = other_element.getValue();

        Integer __this__limitMap_copy_key = other_element_key;

        LimitGroup __this__limitMap_copy_value = new LimitGroup(other_element_value);

        __this__limitMap.put(__this__limitMap_copy_key, __this__limitMap_copy_value);
      }
      this.limitMap = __this__limitMap;
    }
  }

  public LimitConfgTable deepCopy() {
    return new LimitConfgTable(this);
  }

  @Override
  public void clear() {
    this.limitMap = null;
  }

  public int getLimitMapSize() {
    return (this.limitMap == null) ? 0 : this.limitMap.size();
  }

  public void putToLimitMap(int key, LimitGroup val) {
    if (this.limitMap == null) {
      this.limitMap = new HashMap<Integer,LimitGroup>();
    }
    this.limitMap.put(key, val);
  }

  public Map<Integer,LimitGroup> getLimitMap() {
    return this.limitMap;
  }

  public LimitConfgTable setLimitMap(Map<Integer,LimitGroup> limitMap) {
    this.limitMap = limitMap;
    return this;
  }

  public void unsetLimitMap() {
    this.limitMap = null;
  }

  /** Returns true if field limitMap is set (has been assigned a value) and false otherwise */
  public boolean isSetLimitMap() {
    return this.limitMap != null;
  }

  public void setLimitMapIsSet(boolean value) {
    if (!value) {
      this.limitMap = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case LIMIT_MAP:
      if (value == null) {
        unsetLimitMap();
      } else {
        setLimitMap((Map<Integer,LimitGroup>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case LIMIT_MAP:
      return getLimitMap();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case LIMIT_MAP:
      return isSetLimitMap();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof LimitConfgTable)
      return this.equals((LimitConfgTable)that);
    return false;
  }

  public boolean equals(LimitConfgTable that) {
    if (that == null)
      return false;

    boolean this_present_limitMap = true && this.isSetLimitMap();
    boolean that_present_limitMap = true && that.isSetLimitMap();
    if (this_present_limitMap || that_present_limitMap) {
      if (!(this_present_limitMap && that_present_limitMap))
        return false;
      if (!this.limitMap.equals(that.limitMap))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(LimitConfgTable other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetLimitMap()).compareTo(other.isSetLimitMap());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLimitMap()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.limitMap, other.limitMap);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("LimitConfgTable(");
    boolean first = true;

    sb.append("limitMap:");
    if (this.limitMap == null) {
      sb.append("null");
    } else {
      sb.append(this.limitMap);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class LimitConfgTableStandardSchemeFactory implements SchemeFactory {
    public LimitConfgTableStandardScheme getScheme() {
      return new LimitConfgTableStandardScheme();
    }
  }

  private static class LimitConfgTableStandardScheme extends StandardScheme<LimitConfgTable> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, LimitConfgTable struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LIMIT_MAP
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map0 = iprot.readMapBegin();
                struct.limitMap = new HashMap<Integer,LimitGroup>(2*_map0.size);
                for (int _i1 = 0; _i1 < _map0.size; ++_i1)
                {
                  int _key2;
                  LimitGroup _val3;
                  _key2 = iprot.readI32();
                  _val3 = new LimitGroup();
                  _val3.read(iprot);
                  struct.limitMap.put(_key2, _val3);
                }
                iprot.readMapEnd();
              }
              struct.setLimitMapIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, LimitConfgTable struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.limitMap != null) {
        oprot.writeFieldBegin(LIMIT_MAP_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.STRUCT, struct.limitMap.size()));
          for (Map.Entry<Integer, LimitGroup> _iter4 : struct.limitMap.entrySet())
          {
            oprot.writeI32(_iter4.getKey());
            _iter4.getValue().write(oprot);
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class LimitConfgTableTupleSchemeFactory implements SchemeFactory {
    public LimitConfgTableTupleScheme getScheme() {
      return new LimitConfgTableTupleScheme();
    }
  }

  private static class LimitConfgTableTupleScheme extends TupleScheme<LimitConfgTable> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, LimitConfgTable struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetLimitMap()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetLimitMap()) {
        {
          oprot.writeI32(struct.limitMap.size());
          for (Map.Entry<Integer, LimitGroup> _iter5 : struct.limitMap.entrySet())
          {
            oprot.writeI32(_iter5.getKey());
            _iter5.getValue().write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, LimitConfgTable struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TMap _map6 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.limitMap = new HashMap<Integer,LimitGroup>(2*_map6.size);
          for (int _i7 = 0; _i7 < _map6.size; ++_i7)
          {
            int _key8;
            LimitGroup _val9;
            _key8 = iprot.readI32();
            _val9 = new LimitGroup();
            _val9.read(iprot);
            struct.limitMap.put(_key8, _val9);
          }
        }
        struct.setLimitMapIsSet(true);
      }
    }
  }

}

