/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MessageConfigTable implements org.apache.thrift.TBase<MessageConfigTable, MessageConfigTable._Fields>, java.io.Serializable, Cloneable, Comparable<MessageConfigTable> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MessageConfigTable");

  private static final org.apache.thrift.protocol.TField MESSAGE_MAP_FIELD_DESC = new org.apache.thrift.protocol.TField("messageMap", org.apache.thrift.protocol.TType.MAP, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MessageConfigTableStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MessageConfigTableTupleSchemeFactory());
  }

  public Map<String,Map<Integer,String>> messageMap; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MESSAGE_MAP((short)1, "messageMap");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MESSAGE_MAP
          return MESSAGE_MAP;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MESSAGE_MAP, new org.apache.thrift.meta_data.FieldMetaData("messageMap", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32), 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MessageConfigTable.class, metaDataMap);
  }

  public MessageConfigTable() {
  }

  public MessageConfigTable(
    Map<String,Map<Integer,String>> messageMap)
  {
    this();
    this.messageMap = messageMap;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MessageConfigTable(MessageConfigTable other) {
    if (other.isSetMessageMap()) {
      Map<String,Map<Integer,String>> __this__messageMap = new HashMap<String,Map<Integer,String>>(other.messageMap.size());
      for (Map.Entry<String, Map<Integer,String>> other_element : other.messageMap.entrySet()) {

        String other_element_key = other_element.getKey();
        Map<Integer,String> other_element_value = other_element.getValue();

        String __this__messageMap_copy_key = other_element_key;

        Map<Integer,String> __this__messageMap_copy_value = new HashMap<Integer,String>(other_element_value);

        __this__messageMap.put(__this__messageMap_copy_key, __this__messageMap_copy_value);
      }
      this.messageMap = __this__messageMap;
    }
  }

  public MessageConfigTable deepCopy() {
    return new MessageConfigTable(this);
  }

  @Override
  public void clear() {
    this.messageMap = null;
  }

  public int getMessageMapSize() {
    return (this.messageMap == null) ? 0 : this.messageMap.size();
  }

  public void putToMessageMap(String key, Map<Integer,String> val) {
    if (this.messageMap == null) {
      this.messageMap = new HashMap<String,Map<Integer,String>>();
    }
    this.messageMap.put(key, val);
  }

  public Map<String,Map<Integer,String>> getMessageMap() {
    return this.messageMap;
  }

  public MessageConfigTable setMessageMap(Map<String,Map<Integer,String>> messageMap) {
    this.messageMap = messageMap;
    return this;
  }

  public void unsetMessageMap() {
    this.messageMap = null;
  }

  /** Returns true if field messageMap is set (has been assigned a value) and false otherwise */
  public boolean isSetMessageMap() {
    return this.messageMap != null;
  }

  public void setMessageMapIsSet(boolean value) {
    if (!value) {
      this.messageMap = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MESSAGE_MAP:
      if (value == null) {
        unsetMessageMap();
      } else {
        setMessageMap((Map<String,Map<Integer,String>>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MESSAGE_MAP:
      return getMessageMap();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MESSAGE_MAP:
      return isSetMessageMap();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MessageConfigTable)
      return this.equals((MessageConfigTable)that);
    return false;
  }

  public boolean equals(MessageConfigTable that) {
    if (that == null)
      return false;

    boolean this_present_messageMap = true && this.isSetMessageMap();
    boolean that_present_messageMap = true && that.isSetMessageMap();
    if (this_present_messageMap || that_present_messageMap) {
      if (!(this_present_messageMap && that_present_messageMap))
        return false;
      if (!this.messageMap.equals(that.messageMap))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(MessageConfigTable other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMessageMap()).compareTo(other.isSetMessageMap());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMessageMap()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.messageMap, other.messageMap);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MessageConfigTable(");
    boolean first = true;

    sb.append("messageMap:");
    if (this.messageMap == null) {
      sb.append("null");
    } else {
      sb.append(this.messageMap);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MessageConfigTableStandardSchemeFactory implements SchemeFactory {
    public MessageConfigTableStandardScheme getScheme() {
      return new MessageConfigTableStandardScheme();
    }
  }

  private static class MessageConfigTableStandardScheme extends StandardScheme<MessageConfigTable> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MessageConfigTable struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MESSAGE_MAP
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map60 = iprot.readMapBegin();
                struct.messageMap = new HashMap<String,Map<Integer,String>>(2*_map60.size);
                for (int _i61 = 0; _i61 < _map60.size; ++_i61)
                {
                  String _key62;
                  Map<Integer,String> _val63;
                  _key62 = iprot.readString();
                  {
                    org.apache.thrift.protocol.TMap _map64 = iprot.readMapBegin();
                    _val63 = new HashMap<Integer,String>(2*_map64.size);
                    for (int _i65 = 0; _i65 < _map64.size; ++_i65)
                    {
                      int _key66;
                      String _val67;
                      _key66 = iprot.readI32();
                      _val67 = iprot.readString();
                      _val63.put(_key66, _val67);
                    }
                    iprot.readMapEnd();
                  }
                  struct.messageMap.put(_key62, _val63);
                }
                iprot.readMapEnd();
              }
              struct.setMessageMapIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MessageConfigTable struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.messageMap != null) {
        oprot.writeFieldBegin(MESSAGE_MAP_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.MAP, struct.messageMap.size()));
          for (Map.Entry<String, Map<Integer,String>> _iter68 : struct.messageMap.entrySet())
          {
            oprot.writeString(_iter68.getKey());
            {
              oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.STRING, _iter68.getValue().size()));
              for (Map.Entry<Integer, String> _iter69 : _iter68.getValue().entrySet())
              {
                oprot.writeI32(_iter69.getKey());
                oprot.writeString(_iter69.getValue());
              }
              oprot.writeMapEnd();
            }
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MessageConfigTableTupleSchemeFactory implements SchemeFactory {
    public MessageConfigTableTupleScheme getScheme() {
      return new MessageConfigTableTupleScheme();
    }
  }

  private static class MessageConfigTableTupleScheme extends TupleScheme<MessageConfigTable> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MessageConfigTable struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMessageMap()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetMessageMap()) {
        {
          oprot.writeI32(struct.messageMap.size());
          for (Map.Entry<String, Map<Integer,String>> _iter70 : struct.messageMap.entrySet())
          {
            oprot.writeString(_iter70.getKey());
            {
              oprot.writeI32(_iter70.getValue().size());
              for (Map.Entry<Integer, String> _iter71 : _iter70.getValue().entrySet())
              {
                oprot.writeI32(_iter71.getKey());
                oprot.writeString(_iter71.getValue());
              }
            }
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MessageConfigTable struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TMap _map72 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.MAP, iprot.readI32());
          struct.messageMap = new HashMap<String,Map<Integer,String>>(2*_map72.size);
          for (int _i73 = 0; _i73 < _map72.size; ++_i73)
          {
            String _key74;
            Map<Integer,String> _val75;
            _key74 = iprot.readString();
            {
              org.apache.thrift.protocol.TMap _map76 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
              _val75 = new HashMap<Integer,String>(2*_map76.size);
              for (int _i77 = 0; _i77 < _map76.size; ++_i77)
              {
                int _key78;
                String _val79;
                _key78 = iprot.readI32();
                _val79 = iprot.readString();
                _val75.put(_key78, _val79);
              }
            }
            struct.messageMap.put(_key74, _val75);
          }
        }
        struct.setMessageMapIsSet(true);
      }
    }
  }

}

