/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MusicGameSettingTable implements org.apache.thrift.TBase<MusicGameSettingTable, MusicGameSettingTable._Fields>, java.io.Serializable, Cloneable, Comparable<MusicGameSettingTable> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MusicGameSettingTable");

  private static final org.apache.thrift.protocol.TField MUSIC_CONFIG_MAP_FIELD_DESC = new org.apache.thrift.protocol.TField("musicConfigMap", org.apache.thrift.protocol.TType.MAP, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MusicGameSettingTableStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MusicGameSettingTableTupleSchemeFactory());
  }

  public Map<Integer,MusicGameNoteKeyConfig> musicConfigMap; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MUSIC_CONFIG_MAP((short)1, "musicConfigMap");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MUSIC_CONFIG_MAP
          return MUSIC_CONFIG_MAP;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MUSIC_CONFIG_MAP, new org.apache.thrift.meta_data.FieldMetaData("musicConfigMap", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, MusicGameNoteKeyConfig.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MusicGameSettingTable.class, metaDataMap);
  }

  public MusicGameSettingTable() {
  }

  public MusicGameSettingTable(
    Map<Integer,MusicGameNoteKeyConfig> musicConfigMap)
  {
    this();
    this.musicConfigMap = musicConfigMap;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MusicGameSettingTable(MusicGameSettingTable other) {
    if (other.isSetMusicConfigMap()) {
      Map<Integer,MusicGameNoteKeyConfig> __this__musicConfigMap = new HashMap<Integer,MusicGameNoteKeyConfig>(other.musicConfigMap.size());
      for (Map.Entry<Integer, MusicGameNoteKeyConfig> other_element : other.musicConfigMap.entrySet()) {

        Integer other_element_key = other_element.getKey();
        MusicGameNoteKeyConfig other_element_value = other_element.getValue();

        Integer __this__musicConfigMap_copy_key = other_element_key;

        MusicGameNoteKeyConfig __this__musicConfigMap_copy_value = new MusicGameNoteKeyConfig(other_element_value);

        __this__musicConfigMap.put(__this__musicConfigMap_copy_key, __this__musicConfigMap_copy_value);
      }
      this.musicConfigMap = __this__musicConfigMap;
    }
  }

  public MusicGameSettingTable deepCopy() {
    return new MusicGameSettingTable(this);
  }

  @Override
  public void clear() {
    this.musicConfigMap = null;
  }

  public int getMusicConfigMapSize() {
    return (this.musicConfigMap == null) ? 0 : this.musicConfigMap.size();
  }

  public void putToMusicConfigMap(int key, MusicGameNoteKeyConfig val) {
    if (this.musicConfigMap == null) {
      this.musicConfigMap = new HashMap<Integer,MusicGameNoteKeyConfig>();
    }
    this.musicConfigMap.put(key, val);
  }

  public Map<Integer,MusicGameNoteKeyConfig> getMusicConfigMap() {
    return this.musicConfigMap;
  }

  public MusicGameSettingTable setMusicConfigMap(Map<Integer,MusicGameNoteKeyConfig> musicConfigMap) {
    this.musicConfigMap = musicConfigMap;
    return this;
  }

  public void unsetMusicConfigMap() {
    this.musicConfigMap = null;
  }

  /** Returns true if field musicConfigMap is set (has been assigned a value) and false otherwise */
  public boolean isSetMusicConfigMap() {
    return this.musicConfigMap != null;
  }

  public void setMusicConfigMapIsSet(boolean value) {
    if (!value) {
      this.musicConfigMap = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MUSIC_CONFIG_MAP:
      if (value == null) {
        unsetMusicConfigMap();
      } else {
        setMusicConfigMap((Map<Integer,MusicGameNoteKeyConfig>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MUSIC_CONFIG_MAP:
      return getMusicConfigMap();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MUSIC_CONFIG_MAP:
      return isSetMusicConfigMap();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MusicGameSettingTable)
      return this.equals((MusicGameSettingTable)that);
    return false;
  }

  public boolean equals(MusicGameSettingTable that) {
    if (that == null)
      return false;

    boolean this_present_musicConfigMap = true && this.isSetMusicConfigMap();
    boolean that_present_musicConfigMap = true && that.isSetMusicConfigMap();
    if (this_present_musicConfigMap || that_present_musicConfigMap) {
      if (!(this_present_musicConfigMap && that_present_musicConfigMap))
        return false;
      if (!this.musicConfigMap.equals(that.musicConfigMap))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(MusicGameSettingTable other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMusicConfigMap()).compareTo(other.isSetMusicConfigMap());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMusicConfigMap()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.musicConfigMap, other.musicConfigMap);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MusicGameSettingTable(");
    boolean first = true;

    sb.append("musicConfigMap:");
    if (this.musicConfigMap == null) {
      sb.append("null");
    } else {
      sb.append(this.musicConfigMap);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MusicGameSettingTableStandardSchemeFactory implements SchemeFactory {
    public MusicGameSettingTableStandardScheme getScheme() {
      return new MusicGameSettingTableStandardScheme();
    }
  }

  private static class MusicGameSettingTableStandardScheme extends StandardScheme<MusicGameSettingTable> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MusicGameSettingTable struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MUSIC_CONFIG_MAP
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map246 = iprot.readMapBegin();
                struct.musicConfigMap = new HashMap<Integer,MusicGameNoteKeyConfig>(2*_map246.size);
                for (int _i247 = 0; _i247 < _map246.size; ++_i247)
                {
                  int _key248;
                  MusicGameNoteKeyConfig _val249;
                  _key248 = iprot.readI32();
                  _val249 = new MusicGameNoteKeyConfig();
                  _val249.read(iprot);
                  struct.musicConfigMap.put(_key248, _val249);
                }
                iprot.readMapEnd();
              }
              struct.setMusicConfigMapIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MusicGameSettingTable struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.musicConfigMap != null) {
        oprot.writeFieldBegin(MUSIC_CONFIG_MAP_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.STRUCT, struct.musicConfigMap.size()));
          for (Map.Entry<Integer, MusicGameNoteKeyConfig> _iter250 : struct.musicConfigMap.entrySet())
          {
            oprot.writeI32(_iter250.getKey());
            _iter250.getValue().write(oprot);
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MusicGameSettingTableTupleSchemeFactory implements SchemeFactory {
    public MusicGameSettingTableTupleScheme getScheme() {
      return new MusicGameSettingTableTupleScheme();
    }
  }

  private static class MusicGameSettingTableTupleScheme extends TupleScheme<MusicGameSettingTable> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MusicGameSettingTable struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMusicConfigMap()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetMusicConfigMap()) {
        {
          oprot.writeI32(struct.musicConfigMap.size());
          for (Map.Entry<Integer, MusicGameNoteKeyConfig> _iter251 : struct.musicConfigMap.entrySet())
          {
            oprot.writeI32(_iter251.getKey());
            _iter251.getValue().write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MusicGameSettingTable struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TMap _map252 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.musicConfigMap = new HashMap<Integer,MusicGameNoteKeyConfig>(2*_map252.size);
          for (int _i253 = 0; _i253 < _map252.size; ++_i253)
          {
            int _key254;
            MusicGameNoteKeyConfig _val255;
            _key254 = iprot.readI32();
            _val255 = new MusicGameNoteKeyConfig();
            _val255.read(iprot);
            struct.musicConfigMap.put(_key254, _val255);
          }
        }
        struct.setMusicConfigMapIsSet(true);
      }
    }
  }

}

