/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class RegularityGameSettingTable implements org.apache.thrift.TBase<RegularityGameSettingTable, RegularityGameSettingTable._Fields>, java.io.Serializable, Cloneable, Comparable<RegularityGameSettingTable> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RegularityGameSettingTable");

  private static final org.apache.thrift.protocol.TField PLAY_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("playTime", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField PLAY_COUNT_LIMIT_FIELD_DESC = new org.apache.thrift.protocol.TField("playCountLimit", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new RegularityGameSettingTableStandardSchemeFactory());
    schemes.put(TupleScheme.class, new RegularityGameSettingTableTupleSchemeFactory());
  }

  public int playTime; // required
  public int playCountLimit; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PLAY_TIME((short)1, "playTime"),
    PLAY_COUNT_LIMIT((short)2, "playCountLimit");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PLAY_TIME
          return PLAY_TIME;
        case 2: // PLAY_COUNT_LIMIT
          return PLAY_COUNT_LIMIT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PLAYTIME_ISSET_ID = 0;
  private static final int __PLAYCOUNTLIMIT_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PLAY_TIME, new org.apache.thrift.meta_data.FieldMetaData("playTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.PLAY_COUNT_LIMIT, new org.apache.thrift.meta_data.FieldMetaData("playCountLimit", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RegularityGameSettingTable.class, metaDataMap);
  }

  public RegularityGameSettingTable() {
  }

  public RegularityGameSettingTable(
    int playTime,
    int playCountLimit)
  {
    this();
    this.playTime = playTime;
    setPlayTimeIsSet(true);
    this.playCountLimit = playCountLimit;
    setPlayCountLimitIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RegularityGameSettingTable(RegularityGameSettingTable other) {
    __isset_bitfield = other.__isset_bitfield;
    this.playTime = other.playTime;
    this.playCountLimit = other.playCountLimit;
  }

  public RegularityGameSettingTable deepCopy() {
    return new RegularityGameSettingTable(this);
  }

  @Override
  public void clear() {
    setPlayTimeIsSet(false);
    this.playTime = 0;
    setPlayCountLimitIsSet(false);
    this.playCountLimit = 0;
  }

  public int getPlayTime() {
    return this.playTime;
  }

  public RegularityGameSettingTable setPlayTime(int playTime) {
    this.playTime = playTime;
    setPlayTimeIsSet(true);
    return this;
  }

  public void unsetPlayTime() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PLAYTIME_ISSET_ID);
  }

  /** Returns true if field playTime is set (has been assigned a value) and false otherwise */
  public boolean isSetPlayTime() {
    return EncodingUtils.testBit(__isset_bitfield, __PLAYTIME_ISSET_ID);
  }

  public void setPlayTimeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PLAYTIME_ISSET_ID, value);
  }

  public int getPlayCountLimit() {
    return this.playCountLimit;
  }

  public RegularityGameSettingTable setPlayCountLimit(int playCountLimit) {
    this.playCountLimit = playCountLimit;
    setPlayCountLimitIsSet(true);
    return this;
  }

  public void unsetPlayCountLimit() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PLAYCOUNTLIMIT_ISSET_ID);
  }

  /** Returns true if field playCountLimit is set (has been assigned a value) and false otherwise */
  public boolean isSetPlayCountLimit() {
    return EncodingUtils.testBit(__isset_bitfield, __PLAYCOUNTLIMIT_ISSET_ID);
  }

  public void setPlayCountLimitIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PLAYCOUNTLIMIT_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PLAY_TIME:
      if (value == null) {
        unsetPlayTime();
      } else {
        setPlayTime((Integer)value);
      }
      break;

    case PLAY_COUNT_LIMIT:
      if (value == null) {
        unsetPlayCountLimit();
      } else {
        setPlayCountLimit((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PLAY_TIME:
      return Integer.valueOf(getPlayTime());

    case PLAY_COUNT_LIMIT:
      return Integer.valueOf(getPlayCountLimit());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PLAY_TIME:
      return isSetPlayTime();
    case PLAY_COUNT_LIMIT:
      return isSetPlayCountLimit();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof RegularityGameSettingTable)
      return this.equals((RegularityGameSettingTable)that);
    return false;
  }

  public boolean equals(RegularityGameSettingTable that) {
    if (that == null)
      return false;

    boolean this_present_playTime = true;
    boolean that_present_playTime = true;
    if (this_present_playTime || that_present_playTime) {
      if (!(this_present_playTime && that_present_playTime))
        return false;
      if (this.playTime != that.playTime)
        return false;
    }

    boolean this_present_playCountLimit = true;
    boolean that_present_playCountLimit = true;
    if (this_present_playCountLimit || that_present_playCountLimit) {
      if (!(this_present_playCountLimit && that_present_playCountLimit))
        return false;
      if (this.playCountLimit != that.playCountLimit)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(RegularityGameSettingTable other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPlayTime()).compareTo(other.isSetPlayTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPlayTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.playTime, other.playTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPlayCountLimit()).compareTo(other.isSetPlayCountLimit());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPlayCountLimit()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.playCountLimit, other.playCountLimit);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("RegularityGameSettingTable(");
    boolean first = true;

    sb.append("playTime:");
    sb.append(this.playTime);
    first = false;
    if (!first) sb.append(", ");
    sb.append("playCountLimit:");
    sb.append(this.playCountLimit);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RegularityGameSettingTableStandardSchemeFactory implements SchemeFactory {
    public RegularityGameSettingTableStandardScheme getScheme() {
      return new RegularityGameSettingTableStandardScheme();
    }
  }

  private static class RegularityGameSettingTableStandardScheme extends StandardScheme<RegularityGameSettingTable> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RegularityGameSettingTable struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PLAY_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.playTime = iprot.readI32();
              struct.setPlayTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PLAY_COUNT_LIMIT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.playCountLimit = iprot.readI32();
              struct.setPlayCountLimitIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RegularityGameSettingTable struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(PLAY_TIME_FIELD_DESC);
      oprot.writeI32(struct.playTime);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(PLAY_COUNT_LIMIT_FIELD_DESC);
      oprot.writeI32(struct.playCountLimit);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RegularityGameSettingTableTupleSchemeFactory implements SchemeFactory {
    public RegularityGameSettingTableTupleScheme getScheme() {
      return new RegularityGameSettingTableTupleScheme();
    }
  }

  private static class RegularityGameSettingTableTupleScheme extends TupleScheme<RegularityGameSettingTable> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RegularityGameSettingTable struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPlayTime()) {
        optionals.set(0);
      }
      if (struct.isSetPlayCountLimit()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetPlayTime()) {
        oprot.writeI32(struct.playTime);
      }
      if (struct.isSetPlayCountLimit()) {
        oprot.writeI32(struct.playCountLimit);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RegularityGameSettingTable struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.playTime = iprot.readI32();
        struct.setPlayTimeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.playCountLimit = iprot.readI32();
        struct.setPlayCountLimitIsSet(true);
      }
    }
  }

}

