/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class StateConflictConfig implements org.apache.thrift.TBase<StateConflictConfig, StateConflictConfig._Fields>, java.io.Serializable, Cloneable, Comparable<StateConflictConfig> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("StateConflictConfig");

  private static final org.apache.thrift.protocol.TField STATE_CONFLICT_MAP_FIELD_DESC = new org.apache.thrift.protocol.TField("stateConflictMap", org.apache.thrift.protocol.TType.MAP, (short)10);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new StateConflictConfigStandardSchemeFactory());
    schemes.put(TupleScheme.class, new StateConflictConfigTupleSchemeFactory());
  }

  public Map<Integer,List<StateConflictConfigElement>> stateConflictMap; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    STATE_CONFLICT_MAP((short)10, "stateConflictMap");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 10: // STATE_CONFLICT_MAP
          return STATE_CONFLICT_MAP;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.STATE_CONFLICT_MAP, new org.apache.thrift.meta_data.FieldMetaData("stateConflictMap", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32), 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, StateConflictConfigElement.class)))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(StateConflictConfig.class, metaDataMap);
  }

  public StateConflictConfig() {
  }

  public StateConflictConfig(
    Map<Integer,List<StateConflictConfigElement>> stateConflictMap)
  {
    this();
    this.stateConflictMap = stateConflictMap;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public StateConflictConfig(StateConflictConfig other) {
    if (other.isSetStateConflictMap()) {
      Map<Integer,List<StateConflictConfigElement>> __this__stateConflictMap = new HashMap<Integer,List<StateConflictConfigElement>>(other.stateConflictMap.size());
      for (Map.Entry<Integer, List<StateConflictConfigElement>> other_element : other.stateConflictMap.entrySet()) {

        Integer other_element_key = other_element.getKey();
        List<StateConflictConfigElement> other_element_value = other_element.getValue();

        Integer __this__stateConflictMap_copy_key = other_element_key;

        List<StateConflictConfigElement> __this__stateConflictMap_copy_value = new ArrayList<StateConflictConfigElement>(other_element_value.size());
        for (StateConflictConfigElement other_element_value_element : other_element_value) {
          __this__stateConflictMap_copy_value.add(new StateConflictConfigElement(other_element_value_element));
        }

        __this__stateConflictMap.put(__this__stateConflictMap_copy_key, __this__stateConflictMap_copy_value);
      }
      this.stateConflictMap = __this__stateConflictMap;
    }
  }

  public StateConflictConfig deepCopy() {
    return new StateConflictConfig(this);
  }

  @Override
  public void clear() {
    this.stateConflictMap = null;
  }

  public int getStateConflictMapSize() {
    return (this.stateConflictMap == null) ? 0 : this.stateConflictMap.size();
  }

  public void putToStateConflictMap(int key, List<StateConflictConfigElement> val) {
    if (this.stateConflictMap == null) {
      this.stateConflictMap = new HashMap<Integer,List<StateConflictConfigElement>>();
    }
    this.stateConflictMap.put(key, val);
  }

  public Map<Integer,List<StateConflictConfigElement>> getStateConflictMap() {
    return this.stateConflictMap;
  }

  public StateConflictConfig setStateConflictMap(Map<Integer,List<StateConflictConfigElement>> stateConflictMap) {
    this.stateConflictMap = stateConflictMap;
    return this;
  }

  public void unsetStateConflictMap() {
    this.stateConflictMap = null;
  }

  /** Returns true if field stateConflictMap is set (has been assigned a value) and false otherwise */
  public boolean isSetStateConflictMap() {
    return this.stateConflictMap != null;
  }

  public void setStateConflictMapIsSet(boolean value) {
    if (!value) {
      this.stateConflictMap = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case STATE_CONFLICT_MAP:
      if (value == null) {
        unsetStateConflictMap();
      } else {
        setStateConflictMap((Map<Integer,List<StateConflictConfigElement>>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case STATE_CONFLICT_MAP:
      return getStateConflictMap();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case STATE_CONFLICT_MAP:
      return isSetStateConflictMap();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof StateConflictConfig)
      return this.equals((StateConflictConfig)that);
    return false;
  }

  public boolean equals(StateConflictConfig that) {
    if (that == null)
      return false;

    boolean this_present_stateConflictMap = true && this.isSetStateConflictMap();
    boolean that_present_stateConflictMap = true && that.isSetStateConflictMap();
    if (this_present_stateConflictMap || that_present_stateConflictMap) {
      if (!(this_present_stateConflictMap && that_present_stateConflictMap))
        return false;
      if (!this.stateConflictMap.equals(that.stateConflictMap))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(StateConflictConfig other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetStateConflictMap()).compareTo(other.isSetStateConflictMap());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStateConflictMap()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.stateConflictMap, other.stateConflictMap);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("StateConflictConfig(");
    boolean first = true;

    sb.append("stateConflictMap:");
    if (this.stateConflictMap == null) {
      sb.append("null");
    } else {
      sb.append(this.stateConflictMap);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class StateConflictConfigStandardSchemeFactory implements SchemeFactory {
    public StateConflictConfigStandardScheme getScheme() {
      return new StateConflictConfigStandardScheme();
    }
  }

  private static class StateConflictConfigStandardScheme extends StandardScheme<StateConflictConfig> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, StateConflictConfig struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 10: // STATE_CONFLICT_MAP
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map72 = iprot.readMapBegin();
                struct.stateConflictMap = new HashMap<Integer,List<StateConflictConfigElement>>(2*_map72.size);
                for (int _i73 = 0; _i73 < _map72.size; ++_i73)
                {
                  int _key74;
                  List<StateConflictConfigElement> _val75;
                  _key74 = iprot.readI32();
                  {
                    org.apache.thrift.protocol.TList _list76 = iprot.readListBegin();
                    _val75 = new ArrayList<StateConflictConfigElement>(_list76.size);
                    for (int _i77 = 0; _i77 < _list76.size; ++_i77)
                    {
                      StateConflictConfigElement _elem78;
                      _elem78 = new StateConflictConfigElement();
                      _elem78.read(iprot);
                      _val75.add(_elem78);
                    }
                    iprot.readListEnd();
                  }
                  struct.stateConflictMap.put(_key74, _val75);
                }
                iprot.readMapEnd();
              }
              struct.setStateConflictMapIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, StateConflictConfig struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.stateConflictMap != null) {
        oprot.writeFieldBegin(STATE_CONFLICT_MAP_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.LIST, struct.stateConflictMap.size()));
          for (Map.Entry<Integer, List<StateConflictConfigElement>> _iter79 : struct.stateConflictMap.entrySet())
          {
            oprot.writeI32(_iter79.getKey());
            {
              oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, _iter79.getValue().size()));
              for (StateConflictConfigElement _iter80 : _iter79.getValue())
              {
                _iter80.write(oprot);
              }
              oprot.writeListEnd();
            }
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class StateConflictConfigTupleSchemeFactory implements SchemeFactory {
    public StateConflictConfigTupleScheme getScheme() {
      return new StateConflictConfigTupleScheme();
    }
  }

  private static class StateConflictConfigTupleScheme extends TupleScheme<StateConflictConfig> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, StateConflictConfig struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetStateConflictMap()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetStateConflictMap()) {
        {
          oprot.writeI32(struct.stateConflictMap.size());
          for (Map.Entry<Integer, List<StateConflictConfigElement>> _iter81 : struct.stateConflictMap.entrySet())
          {
            oprot.writeI32(_iter81.getKey());
            {
              oprot.writeI32(_iter81.getValue().size());
              for (StateConflictConfigElement _iter82 : _iter81.getValue())
              {
                _iter82.write(oprot);
              }
            }
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, StateConflictConfig struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TMap _map83 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.LIST, iprot.readI32());
          struct.stateConflictMap = new HashMap<Integer,List<StateConflictConfigElement>>(2*_map83.size);
          for (int _i84 = 0; _i84 < _map83.size; ++_i84)
          {
            int _key85;
            List<StateConflictConfigElement> _val86;
            _key85 = iprot.readI32();
            {
              org.apache.thrift.protocol.TList _list87 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
              _val86 = new ArrayList<StateConflictConfigElement>(_list87.size);
              for (int _i88 = 0; _i88 < _list87.size; ++_i88)
              {
                StateConflictConfigElement _elem89;
                _elem89 = new StateConflictConfigElement();
                _elem89.read(iprot);
                _val86.add(_elem89);
              }
            }
            struct.stateConflictMap.put(_key85, _val86);
          }
        }
        struct.setStateConflictMapIsSet(true);
      }
    }
  }

}

