/**
 * Autogenerated by UITool
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
 internal partial class UIWindow_TestTemplateView : UIBase
{
		private UIList m_UIListRoomList;
		private UILabel m_LabelName;
		private UIInput m_InputName;

    protected override void AutoRegisterMember()
    {
		m_UIListRoomList = GetChildComponent<UIList>("UIListRoomList");;
		m_LabelName = GetChildComponent<UILabel>("LabelName");;
		m_InputName = GetChildComponent<UIInput>("InputName");;

    }
}