/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NetWork.Auto
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCBattleLogicFrame : TBase
  {
    private List<BattleFrameData> _battleFrameDataList;

    public List<BattleFrameData> BattleFrameDataList
    {
      get
      {
        return _battleFrameDataList;
      }
      set
      {
        __isset.battleFrameDataList = true;
        this._battleFrameDataList = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool battleFrameDataList;
    }

    public SCBattleLogicFrame() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.List) {
              {
                BattleFrameDataList = new List<BattleFrameData>();
                TList _list8 = iprot.ReadListBegin();
                for( int _i9 = 0; _i9 < _list8.Count; ++_i9)
                {
                  BattleFrameData _elem10 = new BattleFrameData();
                  _elem10 = new BattleFrameData();
                  _elem10.Read(iprot);
                  BattleFrameDataList.Add(_elem10);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCBattleLogicFrame");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (BattleFrameDataList != null && __isset.battleFrameDataList) {
        field.Name = "battleFrameDataList";
        field.Type = TType.List;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, BattleFrameDataList.Count));
          foreach (BattleFrameData _iter11 in BattleFrameDataList)
          {
            _iter11.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCBattleLogicFrame(");
      sb.Append("BattleFrameDataList: ");
      sb.Append(BattleFrameDataList);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
