/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class PkgGeneral_DissolutionRoom : TBase
{
  private sbyte _HandleType;

  public sbyte HandleType
  {
    get
    {
      return _HandleType;
    }
    set
    {
      __isset.HandleType = true;
      this._HandleType = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool HandleType;
  }

  public PkgGeneral_DissolutionRoom() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.Byte) {
            HandleType = iprot.ReadByte();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("PkgGeneral_DissolutionRoom");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (__isset.HandleType) {
      field.Name = "HandleType";
      field.Type = TType.Byte;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteByte(HandleType);
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder sb = new StringBuilder("PkgGeneral_DissolutionRoom(");
    sb.Append("HandleType: ");
    sb.Append(HandleType);
    sb.Append(")");
    return sb.ToString();
  }

}

