/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class PkgSToC_RoomList : TBase
{
  private List<SubPkg_RoomInfo> _RoomInfoList;

  public List<SubPkg_RoomInfo> RoomInfoList
  {
    get
    {
      return _RoomInfoList;
    }
    set
    {
      __isset.RoomInfoList = true;
      this._RoomInfoList = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool RoomInfoList;
  }

  public PkgSToC_RoomList() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.List) {
            {
              RoomInfoList = new List<SubPkg_RoomInfo>();
              TList _list12 = iprot.ReadListBegin();
              for( int _i13 = 0; _i13 < _list12.Count; ++_i13)
              {
                SubPkg_RoomInfo _elem14 = new SubPkg_RoomInfo();
                _elem14 = new SubPkg_RoomInfo();
                _elem14.Read(iprot);
                RoomInfoList.Add(_elem14);
              }
              iprot.ReadListEnd();
            }
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("PkgSToC_RoomList");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (RoomInfoList != null && __isset.RoomInfoList) {
      field.Name = "RoomInfoList";
      field.Type = TType.List;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      {
        oprot.WriteListBegin(new TList(TType.Struct, RoomInfoList.Count));
        foreach (SubPkg_RoomInfo _iter15 in RoomInfoList)
        {
          _iter15.Write(oprot);
        }
        oprot.WriteListEnd();
      }
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder sb = new StringBuilder("PkgSToC_RoomList(");
    sb.Append("RoomInfoList: ");
    sb.Append(RoomInfoList);
    sb.Append(")");
    return sb.ToString();
  }

}

