/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class PkgSToC_CreateOrEnterRoomResult : TBase
{
  private sbyte _Result;
  private string _RoomName;

  public sbyte Result
  {
    get
    {
      return _Result;
    }
    set
    {
      __isset.Result = true;
      this._Result = value;
    }
  }

  public string RoomName
  {
    get
    {
      return _RoomName;
    }
    set
    {
      __isset.RoomName = true;
      this._RoomName = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool Result;
    public bool RoomName;
  }

  public PkgSToC_CreateOrEnterRoomResult() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.Byte) {
            Result = iprot.ReadByte();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.String) {
            RoomName = iprot.ReadString();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("PkgSToC_CreateOrEnterRoomResult");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (__isset.Result) {
      field.Name = "Result";
      field.Type = TType.Byte;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteByte(Result);
      oprot.WriteFieldEnd();
    }
    if (RoomName != null && __isset.RoomName) {
      field.Name = "RoomName";
      field.Type = TType.String;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(RoomName);
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder sb = new StringBuilder("PkgSToC_CreateOrEnterRoomResult(");
    sb.Append("Result: ");
    sb.Append(Result);
    sb.Append(",RoomName: ");
    sb.Append(RoomName);
    sb.Append(")");
    return sb.ToString();
  }

}

