/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class SubPkg_RoomDetail : TBase
{
  private sbyte _Position;
  private string _PlayerName;
  private int _MeshId;
  private int _MeshTextureId;
  private int _BulletId;
  private int _BulletTexture;

  public sbyte Position
  {
    get
    {
      return _Position;
    }
    set
    {
      __isset.Position = true;
      this._Position = value;
    }
  }

  public string PlayerName
  {
    get
    {
      return _PlayerName;
    }
    set
    {
      __isset.PlayerName = true;
      this._PlayerName = value;
    }
  }

  public int MeshId
  {
    get
    {
      return _MeshId;
    }
    set
    {
      __isset.MeshId = true;
      this._MeshId = value;
    }
  }

  public int MeshTextureId
  {
    get
    {
      return _MeshTextureId;
    }
    set
    {
      __isset.MeshTextureId = true;
      this._MeshTextureId = value;
    }
  }

  public int BulletId
  {
    get
    {
      return _BulletId;
    }
    set
    {
      __isset.BulletId = true;
      this._BulletId = value;
    }
  }

  public int BulletTexture
  {
    get
    {
      return _BulletTexture;
    }
    set
    {
      __isset.BulletTexture = true;
      this._BulletTexture = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool Position;
    public bool PlayerName;
    public bool MeshId;
    public bool MeshTextureId;
    public bool BulletId;
    public bool BulletTexture;
  }

  public SubPkg_RoomDetail() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.Byte) {
            Position = iprot.ReadByte();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.String) {
            PlayerName = iprot.ReadString();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 3:
          if (field.Type == TType.I32) {
            MeshId = iprot.ReadI32();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 4:
          if (field.Type == TType.I32) {
            MeshTextureId = iprot.ReadI32();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 5:
          if (field.Type == TType.I32) {
            BulletId = iprot.ReadI32();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 6:
          if (field.Type == TType.I32) {
            BulletTexture = iprot.ReadI32();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("SubPkg_RoomDetail");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (__isset.Position) {
      field.Name = "Position";
      field.Type = TType.Byte;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteByte(Position);
      oprot.WriteFieldEnd();
    }
    if (PlayerName != null && __isset.PlayerName) {
      field.Name = "PlayerName";
      field.Type = TType.String;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(PlayerName);
      oprot.WriteFieldEnd();
    }
    if (__isset.MeshId) {
      field.Name = "MeshId";
      field.Type = TType.I32;
      field.ID = 3;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32(MeshId);
      oprot.WriteFieldEnd();
    }
    if (__isset.MeshTextureId) {
      field.Name = "MeshTextureId";
      field.Type = TType.I32;
      field.ID = 4;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32(MeshTextureId);
      oprot.WriteFieldEnd();
    }
    if (__isset.BulletId) {
      field.Name = "BulletId";
      field.Type = TType.I32;
      field.ID = 5;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32(BulletId);
      oprot.WriteFieldEnd();
    }
    if (__isset.BulletTexture) {
      field.Name = "BulletTexture";
      field.Type = TType.I32;
      field.ID = 6;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32(BulletTexture);
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder sb = new StringBuilder("SubPkg_RoomDetail(");
    sb.Append("Position: ");
    sb.Append(Position);
    sb.Append(",PlayerName: ");
    sb.Append(PlayerName);
    sb.Append(",MeshId: ");
    sb.Append(MeshId);
    sb.Append(",MeshTextureId: ");
    sb.Append(MeshTextureId);
    sb.Append(",BulletId: ");
    sb.Append(BulletId);
    sb.Append(",BulletTexture: ");
    sb.Append(BulletTexture);
    sb.Append(")");
    return sb.ToString();
  }

}

