/**
 * Autogenerated by Tool
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 *  RoomModel class name
 *  1 index
 */

public partial class RoomModel : ModelBase
{
    public const int Index = 1;
    public override int GetIndex()
    {
        return Index;
    }
}